services:
  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: orom_db
      POSTGRES_USER: orom_admin
      POSTGRES_PASSWORD: oromPWD4879
    ports:
      - "5432:5432"

  orom_backend:
    container_name: orom_backend
    image: orom_backend
    build:
      context: .
      dockerfile: docker/Dockerfile_Backend
    command: sh -c "
              python orom_backend/manage.py migrate --noinput && 
              python orom_backend/manage.py runserver 0.0.0.0:8000
            "
    restart: always
    volumes:
      - .:/app
      # bind the host's Docker socket into your Django container
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
