# Generated by Django 5.1.1 on 2024-09-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
