# Generated by Django 5.1.1 on 2024-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene_manager', '0002_alter_object_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
