# Generated by Django 5.1 on 2024-09-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_manager', '0001_object_referenceobject_scene_geometricobject_robot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='object_ptr',
        ),
        migrations.DeleteModel(
            name='ReferenceObject',
        ),
        migrations.DeleteModel(
            name='Robot',
        ),
    ]
